version: '2'

services:

### PHP-FPM Container #######################################

    php-fpm:
      build:
        context: .
      volumes:
        - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
        - ./www:/var/www
      expose:
        - "9000"
      # extra_hosts:
      #   - "dockerhost:${DOCKER_HOST_IP}"
      # environment:
      #   - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      networks:
        - backend

### NGINX Server Container ##################################

    nginx:
      build:
        context: ./nginx
      volumes:
        - ./logs/nginx:/var/log/nginx
        - ./nginx/sites:/etc/nginx/sites-available
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend

### Networks Setup ############################################

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

### Volumes Setup #############################################

volumes:
  mysql:
    driver: "local"